# Generated by Django 2.2.3 on 2019-07-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_date',
            new_name='publish_date',
        ),
    ]
