# Generated by Django 2.2.3 on 2019-07-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20190721_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.CharField(max_length=10),
        ),
    ]
